// components/Board.vue
<template>
  <div class="flex relative size-full">
    <div class="flex size-full" ref="boardRef"></div>
    <div class="absolute bottom-0 right-0 m-4">
      <PageSwitcher :page-id="pageId" :total="whiteboard.getPageCount().toString()" @switch="$emit('switch', $event)" />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Operation } from '~/types';
import { Whiteboard } from './whiteboard';
import { renderRoots } from 'sciux';

const boardRef = ref<HTMLDivElement>()
const executed = reactive<string[]>([])

const props = defineProps<{
  operations: Operation[]
  pageId: string
  whiteboard: Whiteboard
}>()

defineEmits<{
  (e: 'switch', direction: 'previous' | 'next'): void
}>()

const render = (pageId: string) => {
  if (!props.whiteboard) return
  const { document } = props.whiteboard.findPage(pageId)!
  if (!document) return
  try {
    const roots = renderRoots(document.children)
    boardRef.value!.replaceChildren(...roots)
  } catch (e) {
    console.error('Failed to render page', pageId, 'error:', e)
  }
}

effect(() => {
  if (props.operations.length < 1) return
  for (const opt of props.operations) {
    if (executed.includes(opt.id)) continue
    switch (opt.type) {
      case 'add-node':
        props.whiteboard.addNode(props.pageId, opt.position, opt.content)
        break
      case 'remove-node':
        props.whiteboard.removeNode(props.pageId, opt.position)
        break
      case 'set-prop':
        props.whiteboard.setProp(props.pageId, opt.position, opt.attr, opt.value)
        break
      case 'set-content':
        props.whiteboard.setContent(props.pageId, opt.position, opt.content)
        break
      case 'remove-prop':
        props.whiteboard.removeProp(props.pageId, opt.position, opt.attr)
        break
      default:
        console.error('Unknown operation:', opt)
    }
    executed.push(opt.id)
  }
  render(props.pageId)
})
</script>

// packages/web/components/board.tsx
import ShikiHighlighter from 'react-shiki'
import { Whiteboard } from './chat/whiteboard'
import { Operation } from '@echoai/shared'

const processedOperations: string[] = []

export function Board({ operations, whiteboard, pageId }: { operations: Operation[], whiteboard: Whiteboard, pageId: string }) {
  for (const operation of operations) {
    if (processedOperations.includes(operation.id)) {
      continue
    }
    processedOperations.push(operation.id)
    switch (operation.type) {
      case 'add-node':
        whiteboard.addNode(pageId, operation.position, operation.content)
        break
      case 'remove-node':
        whiteboard.removeNode(pageId, operation.position)
        break
      case 'set-prop':
        whiteboard.setProp(pageId, operation.position, operation.attr, operation.value)
        break
      case 'set-content':
        whiteboard.setContent(pageId, operation.position, operation.content)
        break
      case 'remove-prop':
        whiteboard.removeProp(pageId, operation.position, operation.attr)
        break
      default:
        console.error('Unknown operation:', operation)
    }
  }

  return (
    <div className='flex size-full'>
      <ShikiHighlighter
        language="html"
        theme="github-dark"
        style={{ whiteSpace: 'pre-wrap', wordWrap: 'break-word', width: '100%' }}
      >
        {whiteboard.processToDocumentString(pageId)}
      </ShikiHighlighter>
    </div>
  )
}
