// components/Input.vue
<template>
  <input class="w-full h-10 bg-white rounded-lg p-2 focus:outline-none resize-none" :placeholder="placeholder"
    :type="type" @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"/>
</template>

<script setup lang="ts">
defineProps<{
  placeholder: string,
  type: string,
  modelValue: string,
}>()

defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()
</script>

// packages/web/components/input.tsx
export default function Input({ setValue, placeholder, type = "text" }: { setValue?: (value: string) => void, placeholder?: string, type?: string }) {
  return (
    <input
      className="w-full h-10 bg-white rounded-lg p-2 focus:outline-none resize-none"
      placeholder={placeholder}
      type={type}
      onChange={(event) => setValue?.(event.target.value)}
    />
  )
}
