// components/MessageBox.vue
<script setup lang="ts">
defineProps<{
  avatar: string
  role: string
  content?: string
}>()

</script>

<template>
  <div class="flex w-full p-2 gap-2 text-sm" :class="role === 'user' ? 'flex-row-reverse' : 'flex-row'">
    <div class="flex-shrink-0 w-8 h-8">
      <img class="w-full h-full rounded-full" :src="avatar" />
    </div>
    <div class="flex-grow min-w-0">
      <div class="w-full h-full bg-[rgba(255,255,255,0.5)] rounded-lg p-4">
        <div class="prose prose-sm max-w-none">
          <MarkdownRenderer :content="content" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/web/components/message-box.tsx
import { marked } from 'marked'

export default function MessageBox(
  props: {
    avatar: string,
    role: 'user' | 'assistant',
    content: string,
  }
) {
  return (
    <div className={`flex w-full p-2 gap-2 text-sm ${props.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
      <div className={`flex w-8 h-8`}>
        <img className="w-full h-full rounded-full" src={props.avatar} />
      </div>
      <div className="flex w-full h-full">
        <div className="w-full h-full bg-[rgba(255,255,255,0.5)] rounded-lg p-2">
          <div dangerouslySetInnerHTML={{ __html: marked(props.content) }} />
        </div>
      </div>
    </div>
  )
}
