// components/UserAvatar.vue
<template>
  <client-only>
    <button class="p-2 rounded-lg hover:bg-gray-100 transition-colors"
      @click="navigateTo(`/auth/${user ? 'signout' : 'signin'}`, { external: true })">
      <template v-if="user">
        <img class="h-6 rounded-full" :src="user.picture || `https://www.gravatar.com/avatar/${avatarHash}`"
          :alt="user.email || '用户头像'" />
      </template>
      <template v-else>
        <Icon name="heroicons:user-circle" class="w-10 h-10 text-gray-400" />
      </template>
    </button>
  </client-only>
</template>

<script setup lang="ts">
import { useLogtoUser, navigateTo } from '#imports';
import { ref, onMounted } from 'vue';
import md5 from 'crypto-js/md5';

const user = useLogtoUser();
const avatarHash = ref('');

onMounted(() => {
  if (user?.email) {
    avatarHash.value = md5(user.email).toString();
  } else {
    avatarHash.value = '';
  }
});
</script>

// packages/web/components/user-avatar.tsx
"use client";

import { PersonIcon } from "@radix-ui/react-icons";
import { createHash } from "crypto";

interface UserAvatarProps {
  isAuthenticated: boolean;
  isUserPanelOpen: boolean;
  setUserPanelOpen: (isOpen: boolean) => void;
  claims: unknown;
  onLogin: () => void;
  onLogout: () => void;
}

export function UserAvatar({
  isAuthenticated,
  claims,
  isUserPanelOpen,
  setUserPanelOpen,
  onLogin,
  onLogout,
}: UserAvatarProps) {
  const email = claims?.email || "";
  const hash = createHash("sha256")
    .update(email.trim().toLowerCase())
    .digest("hex");
  const gravatarUrl = `https://www.gravatar.com/avatar/${hash}`;

  return (
    <>
      <button
        className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
        onClick={() =>
          isAuthenticated ? setUserPanelOpen(!isUserPanelOpen) : onLogin()
        }
      >
        {!isAuthenticated ? (
          <PersonIcon className={`w-5 h-5 text-gray-700`} />
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={gravatarUrl} alt="User" className="w-5 h-5 rounded-full" />
        )}
      </button>
    </>
  );
}
